title: Chuanyi Liu's Homepage
page-top-title: Chuanyi Liu
top-section-bg-text: Obession beats talent.
home-subtitle: Chuanyi Liu&ensp;|&ensp;刘传艺
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
